packages:
  - 'packages/*'
allowBuilds:
  esbuild: true
  workerd: true
minimumReleaseAge: 0
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@1.1.0
peerDependencyRules:
  allowedVersions:
    vite: '1'
