import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { actionsDirectory, toKeys } from './keys.ts';

export const typesDirectory = '.remix/types';

export type GenerateRouteTypesOptions = {
  root?: string;
};

export function generateRouteTypes(options: GenerateRouteTypesOptions = {}) {
  const root = options.root ?? process.cwd();
  const typesRoot = path.join(root, typesDirectory);
  const routesFile = path.join(root, 'app/routes.ts');
  const controllers = fs
    .globSync(`app/${actionsDirectory}/**/controller.{ts,tsx}`, { cwd: root })
    .sort();

  const keep = new Set<string>();

  for (const file of controllers) {
    const keys = toKeys(file);
    const outFile = path.join(typesRoot, path.dirname(file), '+controller.d.ts');
    const routesImport = toImportPath(path.dirname(outFile), routesFile);
    const access = keys.length > 0 ? `.${keys.join('.')}` : '';

    writeIfChanged(
      outFile,
      [
        '// Generated by @discussions/router. Do not edit.',
        "import type { AnyMiddleware, ControllerFor } from '@discussions/router';",
        `import type { routes } from '${routesImport}';`,
        '',
        `export type RouteMap = typeof routes${access};`,
        '',
        'export interface Controller {',
        '  <const middleware extends readonly AnyMiddleware[] = []>(',
        '    controller: ControllerFor<RouteMap, middleware>,',
        '  ): ControllerFor<RouteMap, middleware>;',
        '}',
        '',
      ].join('\n'),
    );
    keep.add(outFile);
  }

  prune(typesRoot, keep);
}

function toImportPath(fromDir: string, file: string) {
  const relative = path.relative(fromDir, file).replaceAll('\\', '/');
  return relative.startsWith('.') ? relative : `./${relative}`;
}

function writeIfChanged(file: string, content: string) {
  if (fs.existsSync(file) && fs.readFileSync(file, 'utf8') === content) return;
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, content);
}

function prune(dir: string, keep: Set<string>) {
  if (!fs.existsSync(dir)) return;

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      prune(full, keep);
      if (fs.readdirSync(full).length === 0) fs.rmdirSync(full);
      continue;
    }
    if (!keep.has(full)) fs.unlinkSync(full);
  }
}

const invokedAsScript =
  process.argv[1] != null &&
  path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);

if (invokedAsScript) {
  generateRouteTypes();
}
