import { createTheme } from 'pitlane/theme';
import * as s from 'pitlane/theme/schema';

const typeRole = () => ({
  size: s.dimension(),
  lineHeight: s.dimension(),
  weight: s.font.weight(),
});

function typeStyle(size: string, lineHeight: string, weight: number) {
  return { size, lineHeight, weight };
}

// Material 3 roles on a neutral surface. Spacing is the 4dp grid.
export const { token: t, Theme } = createTheme({
  schema: {
    color: s.color(),
    spacing: s.scale(),
    type: {
      displayLarge: typeRole(),
      displayMedium: typeRole(),
      displaySmall: typeRole(),
      headlineLarge: typeRole(),
      headlineMedium: typeRole(),
      headlineSmall: typeRole(),
      titleLarge: typeRole(),
      titleMedium: typeRole(),
      titleSmall: typeRole(),
      bodyLarge: typeRole(),
      bodyMedium: typeRole(),
      bodySmall: typeRole(),
      labelLarge: typeRole(),
      labelMedium: typeRole(),
      labelSmall: typeRole(),
    },
    shape: s.dimension(),
    elevation: s.shadow(),
    duration: s.duration(),
    easing: s.easing(),
    size: s.dimension(),
  },
  tokens: {
    color: {
      primary: '#4F46E5',
      onPrimary: '#FFFFFF',
      primaryContainer: '#EEF2FF',
      onPrimaryContainer: '#312E81',
      secondary: '#4B5563',
      onSecondary: '#FFFFFF',
      secondaryContainer: '#F3F4F6',
      onSecondaryContainer: '#1F2937',
      tertiary: '#57534E',
      onTertiary: '#FFFFFF',
      tertiaryContainer: '#F5F5F4',
      onTertiaryContainer: '#1C1917',
      error: '#DC2626',
      onError: '#FFFFFF',
      errorContainer: '#FEE2E2',
      onErrorContainer: '#991B1B',
      success: '#15803D',
      onSuccess: '#FFFFFF',
      successContainer: '#DCFCE7',
      onSuccessContainer: '#14532D',
      surface: '#FFFFFF',
      surfaceDim: '#E5E7EB',
      surfaceBright: '#FFFFFF',
      surfaceContainerLowest: '#FFFFFF',
      surfaceContainerLow: '#F9FAFB',
      surfaceContainer: '#F3F4F6',
      surfaceContainerHigh: '#E5E7EB',
      surfaceContainerHighest: '#D1D5DB',
      onSurface: '#111827',
      onSurfaceVariant: '#4B5563',
      outline: '#D1D5DB',
      outlineVariant: '#E5E7EB',
      inverseSurface: '#111827',
      inverseOnSurface: '#F9FAFB',
      inversePrimary: '#A5B4FC',
      surfaceTint: '#4F46E5',
      scrim: 'rgb(0 0 0 / 0.32)',
      shadow: '#000000',
    },
    spacing: '0.25rem',
    type: {
      displayLarge: typeStyle('3.5625rem', '4rem', 400),
      displayMedium: typeStyle('2.8125rem', '3.25rem', 400),
      displaySmall: typeStyle('2.25rem', '2.75rem', 400),
      headlineLarge: typeStyle('2rem', '2.5rem', 400),
      headlineMedium: typeStyle('1.75rem', '2.25rem', 400),
      headlineSmall: typeStyle('1.5rem', '2rem', 400),
      titleLarge: typeStyle('1.375rem', '1.75rem', 400),
      titleMedium: typeStyle('1rem', '1.5rem', 500),
      titleSmall: typeStyle('0.875rem', '1.25rem', 500),
      bodyLarge: typeStyle('1rem', '1.5rem', 400),
      bodyMedium: typeStyle('0.875rem', '1.25rem', 400),
      bodySmall: typeStyle('0.75rem', '1rem', 400),
      labelLarge: typeStyle('0.875rem', '1.25rem', 500),
      labelMedium: typeStyle('0.75rem', '1rem', 500),
      labelSmall: typeStyle('0.6875rem', '1rem', 500),
    },
    shape: {
      none: '0',
      extraSmall: '0.25rem',
      small: '0.5rem',
      medium: '0.75rem',
      large: '1rem',
      extraLarge: '1.75rem',
      full: '9999px',
    },
    elevation: {
      level1: '0 1px 2px 0 rgb(0 0 0 / 0.05)',
      level2: '0 4px 12px rgb(0 0 0 / 0.08)',
      level3: '0 12px 28px rgb(0 0 0 / 0.12)',
      level4: '0 16px 40px rgb(0 0 0 / 0.14)',
      level5: '0 24px 48px rgb(0 0 0 / 0.16)',
    },
    duration: {
      short1: '50ms',
      short2: '100ms',
      short3: '150ms',
      short4: '200ms',
      medium1: '250ms',
      medium2: '300ms',
      medium3: '350ms',
      medium4: '400ms',
      long1: '450ms',
      long2: '500ms',
      long3: '550ms',
      long4: '600ms',
    },
    easing: {
      standard: 'cubic-bezier(0.2, 0, 0, 1)',
      standardDecelerate: 'cubic-bezier(0, 0, 0, 1)',
      standardAccelerate: 'cubic-bezier(0.3, 0, 1, 1)',
      emphasizedDecelerate: 'cubic-bezier(0.05, 0.7, 0.1, 1)',
      emphasizedAccelerate: 'cubic-bezier(0.3, 0, 0.8, 0.15)',
    },
    size: {
      px: '1px',
      full: '100%',
      screen: '100dvh',
      half: '50%',
      prose: '70%',
      field: 'min(20rem, 100%)',
      page: '64rem',
      preview: '18.75rem',
      toast: '22.25rem',
    },
  },
}).extend((base) => ({
  // M3 state layers are 8% of the on-color. Premultiplied so a single background can use them.
  schema: { state: s.color(), brand: s.color() },
  tokens: {
    state: {
      primary: `color-mix(in oklch, ${base.color.onSurface} 10%, ${base.color.primary})`,
      primaryContainer: `color-mix(in oklch, ${base.color.onPrimaryContainer} 8%, ${base.color.primaryContainer})`,
      errorContainer: `color-mix(in oklch, ${base.color.onErrorContainer} 8%, ${base.color.errorContainer})`,
      inverseSurface: `color-mix(in oklch, ${base.color.inverseOnSurface} 8%, ${base.color.inverseSurface})`,
      surface: `color-mix(in oklch, ${base.color.onSurface} 8%, ${base.color.surfaceContainerLow})`,
      github: 'color-mix(in oklch, #ffffff 12%, #24292f)',
    },
    brand: {
      github: '#24292F',
      onGithub: '#FFFFFF',
    },
    elevation: {
      focus: `0 0 0 1px ${base.color.primary}`,
    },
  },
}));
