create table users (
  id integer generated by default as identity primary key,
  email varchar(255) not null unique,
  name varchar(255) not null,
  avatar varchar(1024),
  email_verified boolean not null default false
);

create table accounts (
  id integer generated by default as identity primary key,
  type varchar(32) not null,
  provider varchar(128),
  provider_account_id varchar(255),
  password varchar(255),
  user_id integer not null references users (id) on delete cascade
);

create table sessions (
  id varchar(255) primary key,
  user_id integer not null references users (id) on delete cascade,
  expires varchar(255) not null
);

create table verification_tokens (
  identifier varchar(255) not null,
  token varchar(255) primary key,
  expires varchar(255) not null
);

create table categories (
  id integer generated by default as identity primary key,
  emoji varchar(32) not null,
  title varchar(255) not null,
  description text not null,
  slug varchar(255) not null unique
);

create table discussions (
  id integer generated by default as identity primary key,
  title varchar(255) not null,
  content text not null,
  category_id integer not null references categories (id) on delete cascade,
  author_id integer not null references users (id) on delete cascade,
  created_at text not null,
  updated_at text not null
);

create table comments (
  id integer generated by default as identity primary key,
  content text not null,
  author_id integer not null references users (id) on delete cascade,
  discussion_id integer not null references discussions (id) on delete cascade,
  created_at text not null,
  updated_at text not null
);

create table discussion_votes (
  user_id integer not null references users (id) on delete cascade,
  discussion_id integer not null references discussions (id) on delete cascade,
  primary key (user_id, discussion_id)
);

create table comment_votes (
  user_id integer not null references users (id) on delete cascade,
  comment_id integer not null references comments (id) on delete cascade,
  primary key (user_id, comment_id)
);
